#ifndef _ERROR_H
#define _ERROR_H
#define NOT_VALID_VARIABLE 49
#define NOT_VALID_VARIABLE_TYPE 50
#define NOT_VALID_INTEGER_TYPE 52
#define INVALID_IDENTIFIER 53
#define INVALID_INTEGER 54

#endif // _ERROR_H
